# SwiftLint default configuration

# Paths to ignore
excluded:
  - Pods
  - Carthage
  - .build

disabled_rules:
  - line_length
  - force_cast
  - force_try
  - todo
  - file_length
  - identifier_name
  - type_name

type_body_length:
  warning: 300
  error: 400

reporter: "xcode" # Options: xcode, json, csv, checkstyle, junit, html

# Strict mode (optional)
strict: true

