# SwiftLint default configuration

# Paths to ignore
excluded:
  - Pods
  - Carthage
  - .build

disabled_rules:
  - void_function_in_ternary
  - function_body_length
  - type_body_length
  - type_name
  - line_length
  - file_length
  - identifier_name
  - todo
  - nesting

reporter: "github-actions-logging"
strict: true
