# SwiftLint default configuration

# Paths to ignore
excluded:
  - Pods
  - Carthage
  - .build

disabled_rules:
  - line_length
  - file_length
  - identifier_name
  - todo

reporter: "github-actions-logging"
strict: true
