struct Quote {
    static let empty: Quote = .init(text: "", attribution: "")
    static let randomQuote: Quote = mainQuotes.randomElement() ?? Quote.empty

    let text: String
    let attribution: String

    var displayString: String {
        if attribution.isEmpty {
            text
        } else {
            "\(text) - \(attribution)"
        }
    }
}

let mainQuotes: [Quote] = [
    Quote(text: "Never in the field of human conflict was so much owed by so many to so few.", attribution: "Winston Churchill"),
    Quote(text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", attribution: "Winston Churchill"),
    Quote(text: "In war there is no prize for the runner-up.", attribution: "General Omar Bradley"),
    Quote(text: "Ours is a world of nuclear giants and ethical infants. We know more about war than we know about peace, more about killing than we know about living.", attribution: "General Omar Bradley"),
    Quote(text: "The soldier above all others prays for peace, for it is the soldier who must suffer and bear the deepest wounds and scars of war.", attribution: "General Douglas MacArthur"),
    Quote(text: "They died hard, those savage men - like wounded wolves at bay. They were filthy, and they were lousy, and they stunk. And I loved them.", attribution: "General Douglas MacArthur"),
    Quote(text: "We must be prepared to make heroic sacrifices for the cause of peace that we make ungrudgingly for the cause of war. There is no task that is more important or closer to my heart.", attribution: "Albert Einstein"),
    Quote(text: "War is an ugly thing, but not the ugliest of things. The decayed and degraded state of moral and patriotic feeling which thinks that nothing is worth war is much worse. The person who has nothing for which he is willing to fight, nothing which is more important than his own personal safety, is a miserable creature, and has no chance of being free unless made or kept so by the exertions of better men than himself.", attribution: "John Stuart Mill"),
    Quote(text: "Future years will never know the seething hell and the black infernal background, the countless minor scenes and interiors of the secession war; and it is best they should not. The real war will never get in the books.", attribution: "Walt Whitman"),
    Quote(text: "There's no honorable way to kill, no gentle way to destroy. There is nothing good in war. Except its ending.", attribution: "Abraham Lincoln"),
    Quote(text: "The death of one man is a tragedy. The death of millions is a statistic.", attribution: "Joseph Stalin"),
    Quote(text: "Death solves all problems - no man, no problem.", attribution: "Joseph Stalin"),
    Quote(text: "In the Soviet army it takes more courage to retreat than advance.", attribution: "Joseph Stalin"),
    Quote(text: "It is foolish and wrong to mourn the men who died. Rather we should thank God that such men lived.", attribution: "General George S. Patton"),
    Quote(text: "Never think that war, no matter how necessary, nor how justified, is not a crime.", attribution: "Ernest Hemingway"),
    Quote(text: "Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.", attribution: "Ernest Hemingway"),
    Quote(text: "All wars are civil wars, because all men are brothers.", attribution: "Francois Fenelon"),
    Quote(text: "I have never advocated war except as a means of peace.", attribution: "Ulysses S. Grant"),
    Quote(text: "Older men declare war. But it is the youth that must fight and die.", attribution: "Herbert Hoover"),
    Quote(text: "Only the dead have seen the end of war.", attribution: "Plato"),
    Quote(text: "Death is nothing, but to live defeated and inglorious is to die daily.", attribution: "Napoleon Bonaparte"),
    Quote(text: "It is well that war is so terrible, or we should get too fond of it.", attribution: "Robert E. Lee"),
    Quote(text: "A soldier will fight long and hard for a bit of colored ribbon.", attribution: "Napoleon Bonaparte"),
    Quote(text: "He who fears being conquered is sure of defeat.", attribution: "Napoleon Bonaparte"),
    Quote(text: "You must not fight too often with one enemy, or you will teach him all your art of war.", attribution: "Napoleon Bonaparte"),
    Quote(text: "There's a graveyard in northern France where all the dead boys from D-Day are buried. The white crosses reach from one horizon to the other. I remember looking it over and thinking it was a forest of graves. But the rows were like this, dizzying, diagonal, perfectly straight, so after all it wasn't a forest but an orchard of graves. Nothing to do with nature, unless you count human nature.", attribution: "Barbara Kingsolver"),
    Quote(text: "If we don't end war, war will end us.", attribution: "H. G. Wells"),
    Quote(text: "From my rotting body, flowers shall grow and I am in them and that is eternity.", attribution: "Edvard Munch"),
    Quote(text: "He who has a thousand friends has not a friend to spare, And he who has one enemy will meet him everywhere.", attribution: "Ali ibn-Abi-Talib"),
    Quote(text: "For the Angel of Death spread his wings on the blast, And breathed in the face of the foe as he pass'd; And the eyes of the sleepers wax'd deadly and chill, And their hearts but once heaved, and for ever grew still!", attribution: "George Gordon Byron, The Destruction of Sennacherib"),
    Quote(text: "They wrote in the old days that it is sweet and fitting to die for one's country. But in modern war, there is nothing sweet nor fitting in your dying. You will die like a dog for no good reason.", attribution: "Ernest Hemingway"),
    Quote(text: "There is many a boy here today who looks on war as all glory, but, boys, it is all hell. You can bear this warning voice to generations yet to come. I look upon war with horror.", attribution: "General William Tecumseh Sherman"),
    Quote(text: "War is as much a punishment to the punisher as it is to the sufferer.", attribution: "Thomas Jefferson"),
    Quote(text: "War would end if the dead could return.", attribution: "Stanley Baldwin"),
    Quote(text: "When you have to kill a man it costs nothing to be polite.", attribution: "Winston Churchill"),
    Quote(text: "Battles are won by slaughter and maneuver. The greater the general, the more he contributes in maneuver, the less he demands in slaughter.", attribution: "Winston Churchill"),
    Quote(text: "History will be kind to me for I intend to write it.", attribution: "Winston Churchill"),
    Quote(text: "We shall defend our island, whatever the cost may be, we shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.", attribution: "Winston Churchill"),
    Quote(text: "When you get to the end of your rope, tie a knot and hang on.", attribution: "Franklin D. Roosevelt"),
    Quote(text: "A hero is no braver than an ordinary man, but he is brave five minutes longer.", attribution: "Ralph Waldo Emerson"),
    Quote(text: "It is a big step to take another human life. It is not to be done lightly.", attribution: "Lt. Col. Tim Collins"),
    Quote(text: "Our greatest glory is not in never failing, but in rising up every time we fail.", attribution: "Ralph Waldo Emerson"),
    Quote(text: "The characteristic of a genuine heroism is its persistency. All men have wandering impulses, fits and starts of generosity. But when you have resolved to be great, abide by yourself, and do not weakly try to reconcile yourself with the world. The heroic cannot be the common, nor the common the heroic.", attribution: "Ralph Waldo Emerson"),
    Quote(text: "If the opposition disarms, well and good. If it refuses to disarm, we shall disarm it ourselves.", attribution: "Joseph Stalin"),
    Quote(text: "The object of war is not to die for your country but to make the other bastard die for his.", attribution: "General George S. Patton"),
    Quote(text: "Better to fight for something than live for nothing.", attribution: "General George S. Patton"),
    Quote(text: "Courage is fear holding on a minute longer.", attribution: "General George S. Patton"),
    Quote(text: "We happy few, we band of brothers / For he today that sheds his blood with me / Shall be my brother.", attribution: "William Shakespeare, King Henry V"),
    Quote(text: "Cowards die many times before their deaths; The valiant never taste of death but once.", attribution: "William Shakespeare, Julius Caesar"),
    Quote(text: "Never interrupt your enemy when he is making a mistake.", attribution: "Napoleon Bonaparte"),
    Quote(text: "There are only two forces in the world, the sword and the spirit. In the long run the sword will always be conquered by the spirit.", attribution: "Napoleon Bonaparte"),
    Quote(text: "There will one day spring from the brain of science a machine or force so fearful in its potentialities, so absolutely terrifying, that even man, the fighter, who will dare torture and death in order to inflict torture and death, will be appalled, and so abandon war forever.", attribution: "Thomas A. Edison"),
    Quote(text: "There are no atheists in foxholes, this isn't an argument against atheism, it's an argument against foxholes.", attribution: "James Morrow"),
    Quote(text: "Live as brave men; and if fortune is adverse, front its blows with brave hearts.", attribution: "Cicero"),
    Quote(text: "Courage and perseverance have a magical talisman, before which difficulties disappear and obstacles vanish into air.", attribution: "John Quincy Adams"),
    Quote(text: "Courage is being scared to death - but saddling up anyway.", attribution: "John Wayne"),
    Quote(text: "Above all things, never be afraid. The enemy who forces you to retreat is himself afraid of you at that very moment.", attribution: "Andre Maurois"),
    Quote(text: "I have never made but one prayer to God, a very short one: 'O Lord, make my enemies ridiculous.' And God granted it.", attribution: "Voltaire"),
    Quote(text: "Safeguarding the rights of others is the most noble and beautiful end of a human being.", attribution: "Kahlil Gibran, The Voice of the Poet"),
    Quote(text: "He conquers who endures.", attribution: "Persius"),
    Quote(text: "It is better to die on your feet than to live on your knees!", attribution: "Emiliano Zapata"),
    Quote(text: "You know the real meaning of peace only if you have been through the war.", attribution: "Kosovar"),
    Quote(text: "Those who have long enjoyed such privileges as we enjoy forget in time that men have died to win them.", attribution: "Franklin D. Roosevelt"),
    Quote(text: "In war there is no substitute for victory.", attribution: "General Douglas MacArthur"),
    Quote(text: "War is a series of catastrophes which result in victory.", attribution: "Georges Clemenceau"),
    Quote(text: "In war, truth is the first casualty.", attribution: "Aeschylus"),
    Quote(text: "Incoming fire has the right of way.", attribution: "Unknown"),
    Quote(text: "Mankind must put an end to war, or war will put an end to mankind.", attribution: "John F. Kennedy"),
    Quote(text: "War does not determine who is right, only who is left.", attribution: "Bertrand Russell"),
    Quote(text: "A ship without Marines is like a garment without buttons.", attribution: "Admiral David D. Porter, USN"),
    Quote(text: "The press is our chief ideological weapon.", attribution: "Nikita Khrushchev"),
    Quote(text: "Whether you like it or not, history is on our side. We will bury you!", attribution: "Nikita Khrushchev"),
    Quote(text: "If the enemy is in range, so are you.", attribution: "Infantry Journal"),
    Quote(text: "Cost of a single Javelin Missile: $80,000", attribution: "Unknown"),
    Quote(text: "Cost of a single Tomahawk Cruise Missile: $900,000", attribution: "Unknown"),
    Quote(text: "Cost of a single F-117A Nighthawk: $122 Million", attribution: "Unknown"),
    Quote(text: "Cost of a single F-22 Raptor: $135 Million", attribution: "Unknown"),
    Quote(text: "Cost of a single AC-130U Gunship: $190 Million", attribution: "Unknown"),
    Quote(text: "Cost of a single B-2 Bomber: $2.2 Billion", attribution: "Unknown"),
    Quote(text: "So long as there are men, there will be wars.", attribution: "Albert Einstein"),
    Quote(text: "Aim towards the Enemy.", attribution: "Instruction printed on US Rocket Launcher"),
    Quote(text: "I think the human race needs to think about killing. How much evil must we do to do good?", attribution: "Robert McNamara"),
    Quote(text: "Any military commander who is honest will admit he makes mistakes in the application of military power.", attribution: "Robert McNamara"),
    Quote(text: "You can make a throne of bayonets, but you can't sit on it for long.", attribution: "Boris Yeltsin"),
    Quote(text: "The deadliest weapon in the world is a Marine and his rifle!", attribution: "General John J. Pershing"),
    Quote(text: "Concentrated power has always been the enemy of liberty.", attribution: "Ronald Reagan"),
    Quote(text: "Whoever stands by a just cause cannot possibly be called a terrorist.", attribution: "Yassar Arafat"),
    Quote(text: "Nothing in life is so exhilarating as to be shot at without result.", attribution: "Winston Churchill"),
    Quote(text: "War is delightful to those who have not yet experienced it.", attribution: "Erasmus"),
    Quote(text: "Friendly fire, isn't.", attribution: "Unknown"),
    Quote(text: "Diplomats are just as essential in starting a war as soldiers are for finishing it.", attribution: "Will Rogers"),
    Quote(text: "I think that technologies are morally neutral until we apply them. It's only when we use them for good or for evil that they become good or evil.", attribution: "William Gibson"),
    Quote(text: "All that is necessary for evil to succeed is for good men to do nothing.", attribution: "Edmund Burke"),
    Quote(text: "The commander in the field is always right and the rear echelon is wrong, unless proved otherwise.", attribution: "Colin Powell"),
    Quote(text: "Freedom is not free, but the U.S. Marine Corps will pay most of your share.", attribution: "Ned Dolan"),
    Quote(text: "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.", attribution: "Albert Einstein"),
    Quote(text: "The truth of the matter is that you always know the right thing to do. The hard part is doing it.", attribution: "Norman Schwarzkopf"),
    Quote(text: "If you know the enemy and know yourself you need not fear the results of a hundred battles.", attribution: "Sun Tzu"),
    Quote(text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", attribution: "Abraham Lincoln"),
    Quote(text: "If we can't persuade nations with comparable values of the merits of our cause, we'd better reexamine our reasoning.", attribution: "Robert McNamara"),
    Quote(text: "The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants.", attribution: "Thomas Jefferson"),
    Quote(text: "If the wings are traveling faster than the fuselage, it's probably a helicopter, and therefore, unsafe.", attribution: "Unknown"),
    Quote(text: "Five second fuses only last three seconds.", attribution: "Infantry Journal"),
    Quote(text: "If your attack is going too well, you're walking into an ambush.", attribution: "Infantry Journal"),
    Quote(text: "No battle plan survives contact with the enemy.", attribution: "Colin Powell"),
    Quote(text: "When the pin is pulled, Mr. Grenade is not our friend.", attribution: "U.S. Army Training Notice"),
    Quote(text: "A man may die, nations may rise and fall, but an idea lives on.", attribution: "John F. Kennedy"),
    Quote(text: "A leader leads by example, not by force.", attribution: "Sun Tzu"),
    Quote(text: "If you can't remember, the claymore is pointed toward you.", attribution: "Unknown"),
    Quote(text: "There are only two kinds of people that understand Marines: Marines and the enemy. Everyone else has a secondhand opinion.", attribution: "General William Thornson"),
    Quote(text: "The more marines I have around, the better I like it.", attribution: "General Clark, U.S. Army"),
    Quote(text: "Never forget that your weapon was made by the lowest bidder.", attribution: "Unknown"),
    Quote(text: "Keep looking below surface appearances. Don't shrink from doing so just because you might not like what you find.", attribution: "Colin Powell"),
    Quote(text: "Try to look unimportant; they may be low on ammo.", attribution: "Infantry Journal"),
    Quote(text: "The world will not accept dictatorship or domination.", attribution: "Mikhail Gorbachev"),
    Quote(text: "Tyrants have always some slight shade of virtue; they support the laws before destroying them.", attribution: "Voltaire"),
    Quote(text: "Heroes may not be braver than anyone else. They're just brave five minutes longer.", attribution: "Ronald Reagan"),
    Quote(text: "In the end, it was luck. We were *this* close to nuclear war, and luck prevented it.", attribution: "Robert McNamara"),
    Quote(text: "Some people live an entire lifetime and wonder if they have ever made a difference in the world, but the Marines don't have that problem.", attribution: "Ronald Reagan"),
    Quote(text: "It is generally inadvisable to eject directly over the area you just bombed.", attribution: "U.S. Air Force Marshal"),
    Quote(text: "We sleep safely in our beds because rough men stand ready in the night to visit violence on those who would harm us.", attribution: "George Orwell (Misattributed, was actually written by Richard Grenier)"),
    Quote(text: "If at first you don't succeed, call an air strike.", attribution: "Unknown"),
    Quote(text: "Tracers work both ways.", attribution: "U.S. Army Ordinance"),
    Quote(text: "Teamwork is essential, it gives them other people to shoot at.", attribution: "Unknown"),
    Quote(text: "The real and lasting victories are those of peace, and not of war.", attribution: "Ralph Waldo Emmerson"),
    Quote(text: "We're in a world in which the possibility of terrorism, married up with technology, could make us very, very sorry we didn't act.", attribution: "Condoleeza Rice"),
    Quote(text: "All warfare is based on deception.", attribution: "Sun Tzu"),
    Quote(text: "The indefinite combination of human infallibility and nuclear weapons will lead to the destruction of nations.", attribution: "Robert McNamara"),
    Quote(text: "In war, you win or lose, live or die and the difference is just an eyelash.", attribution: "General Douglas MacArthur"),
    Quote(text: "You can't say civilization don't advance, for in every war, they kill you in a new way.", attribution: "Will Rogers"),
    Quote(text: "They'll be no learning period with nuclear weapons. Make one mistake and you're going to destroy nations.", attribution: "Robert McNamara"),
    Quote(text: "It doesn't take a hero to order men into battle. It takes a hero to be one of those men who goes into battle.", attribution: "General Norman Schwarzkopf"),
    Quote(text: "Any soldier worth his salt should be antiwar. And still, there are things worth fighting for.", attribution: "General Norman Schwarzkopf"),
    Quote(text: "It is fatal to enter any war without the will to win it.", attribution: "General Douglas MacArthur"),
    Quote(text: "Let your plans be as dark and impenetrable as night, and when you move, fall like a thunderbolt.", attribution: "Sun Tzu"),
    Quote(text: "Anyone, who truly wants to go to war, has truly never been there before!", attribution: "Larry Reeves"),
    Quote(text: "Whoever said the pen is mightier than the sword obviously never encountered automatic weapons.", attribution: "General Douglas MacArthur"),
    Quote(text: "Whoever does not miss the Soviet Union has no heart. Whoever wants it back has no brain.", attribution: "Vladimir Putin"),
    Quote(text: "My first wish is to see this plague of mankind, war, banished from the earth.", attribution: "George Washington"),
    Quote(text: "Cluster bombing from B-52s are very, very, accurate. The bombs are guaranteed to always hit the ground.", attribution: "USAF Ammo Troop"),
    Quote(text: "If a man has done his best, what else is there?", attribution: "General George S. Patton"),
    Quote(text: "The bursting radius of a hand-grenade is always one foot greater than your jumping range.", attribution: "Unknown"),
    Quote(text: "The tyrant always talks as if he's preserving the best interests of his people when he actually acts to undermine them.", attribution: "Ramman Kenoun"),
    Quote(text: "Every tyrant who has lived has believed in freedom - for himself.", attribution: "Elbert Hubbard"),
    Quote(text: "If our country is worth dying for in time of war let us resolve that it is truly worth living for in time of peace.", attribution: "Hamilton Fish"),
    Quote(text: "Nationalism is an infantile disease. It is the measles of mankind.", attribution: "Albert Einstein"),
    Quote(text: "We must not confuse dissent with disloyalty.", attribution: "Edward R Murrow"),
    Quote(text: "I will fight for my country, but I will not lie for her.", attribution: "Zora Neale Hurston"),
    Quote(text: "As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.", attribution: "John F. Kennedy"),
    Quote(text: "An eye for an eye makes the whole world blind.", attribution: "Gandhi"),
    Quote(text: "Traditional nationalism cannot survive the fissioning of the atom. One world or none.", attribution: "Stuart Chase"),
    Quote(text: "If you want a symbolic gesture, don't burn the flag; wash it.", attribution: "Norman Thomas"),
    Quote(text: "The nation is divided, half patriots and half traitors, and no man can tell which from which.", attribution: "Mark Twain"),
    Quote(text: "Patriotism is your conviction that this country is superior to all others because you were born in it.", attribution: "George Bernard Shaw"),
    Quote(text: "If you're ashamed to stand by your colors, you had better seek another flag.", attribution: "Anonymous"),
    Quote(text: "Revenge, at first though sweet, Bitter ere long back on itself recoils.", attribution: "John Milton"),
    Quote(text: "A citizen of America will cross the ocean to fight for democracy, but won't cross the street to vote...", attribution: "Bill Vaughan"),
    Quote(text: "Patriotism is supporting your country all the time, and your government when it deserves it.", attribution: "Mark Twain"),
    Quote(text: "I love America more than any other country in this world; and, exactly for this reason, I insist on the right to criticize her perpetually.", attribution: "James Baldwin"),
    Quote(text: "...dissent, rebellion, and all-around hell-raising remain the true duty of patriots.", attribution: "Barbara Ehrenreich"),
    Quote(text: "Principle is OK up to a certain point, but principle doesn't do any good if you lose.", attribution: "Dick Cheney"),
    Quote(text: "If an injury has to be done to a man it should be so severe that his vengeance need not be feared.", attribution: "Machiavelli"),
    Quote(text: "Before you embark on a journey of revenge, you should first dig two graves.", attribution: "Confucius"),
    Quote(text: "It is lamentable, that to be a good patriot one must become the enemy of the rest of mankind.", attribution: "Voltaire"),
    Quote(text: "Ask not what your country can do for you, but what you can do for your country.", attribution: "John F. Kennedy"),
    Quote(text: "Revenge is profitable.", attribution: "Edward Gibbon"),
    Quote(text: "Patriotism ruins history.", attribution: "Goethe"),
    Quote(text: "I would not say that the future is necessarily less predictable than the past. I think the past was not predictable when it started.", attribution: "Donald Rumsfeld"),
    Quote(text: "I only regret that I have but one life to give for my country.", attribution: "Nathan Hale"),
    Quote(text: "Live well. It is the greatest revenge.", attribution: "The Talmud"),
    Quote(text: "We know where they are. They're in the area around Tikrit and Baghdad and east, west, south and north somewhat.", attribution: "Donald Rumsfeld"),
    Quote(text: "I was born an American; I will live an American; I shall die an American!", attribution: "Daniel Webster"),
    Quote(text: "Patriotism varies, from a noble devotion to a moral lunacy.", attribution: "WR Inge"),
    Quote(text: "It is easy to take liberty for granted when you have never had it taken from you.", attribution: "Dick Cheney"),
    Quote(text: "A man's feet must be planted in his country, but his eyes should survey the world.", attribution: "George Santayana"),
    Quote(text: "One good act of vengeance deserves another.", attribution: "Jon Jefferson"),
    Quote(text: "You cannot get ahead while you are getting even.", attribution: "Dick Armey"),
    Quote(text: "A nation reveals itself not only by the men it produces but also by the men it honors, the men it remembers.", attribution: "John F. Kennedy"),
    Quote(text: "Patriotism is an arbitrary veneration of real estate above principles.", attribution: "George Jean Nathan"),
    Quote(text: "Soldiers usually win the battles and generals get the credit for them.", attribution: "Napoleon Bonaparte"),
    Quote(text: "War is fear cloaked in courage.", attribution: "General William C. Westmoreland"),
    Quote(text: "In peace, sons bury their fathers. In war, fathers bury their sons.", attribution: "Herodotus"),
    Quote(text: "Don't get mad, get even.", attribution: "John F. Kennedy"),
    Quote(text: "A man who would not risk his life for something does not deserve to live.", attribution: "Martin Luther King")
]

let infiniteWarfareGeneralSayings: [Quote] = [
    Quote(text: "The SDF does not allow women to serve as soldiers, only in auxiliary roles.", attribution: "Unknown"),
    Quote(text: "15 years of Military service is mandatory for all SDF males starting at age 12.", attribution: "Unknown"),
    Quote(text: "Admiral Kotch is the original orator of The Front's infamous motto, \"Death is no disgrace\".", attribution: "Unknown"),
    Quote(text: "The Secession Wars were initiated by the SDF to withdraw from the UNSA 30 years ago.", attribution: "Unknown"),
    Quote(text: "Salen Kotch was the youngest recipient ever of The Front's Iron Sword for loyalty.", attribution: "Unknown"),
    Quote(text: "Per capita, The Settlement Defense Front has 900% more soldiers than the UNSA.", attribution: "Unknown"),
    Quote(text: "The SDF was formed decades ago to enforce martial law on off world territories.", attribution: "Unknown"),
    Quote(text: "The \"Settlement Defense Front\" chose its name to give the appearance of a noble underdog.", attribution: "Unknown"),
    Quote(text: "Earth based broadcasts are not permitted in SDF controlled territory.", attribution: "Unknown"),
    Quote(text: "The SDF ranks citizens by loyalty to the regime.", attribution: "Unknown"),
    Quote(text: "Salen Kotch was a proponent for the construction of the supercarrier Olympus Mons.", attribution: "Unknown"),
    Quote(text: "The SDF has an elite propaganda division called \"The Veritas\".", attribution: "Unknown"),
    Quote(text: "The Olympus Mons is the largest battle class warship ever built.", attribution: "Unknown"),
    Quote(text: "The Settlement Defense Front operates forced work camps throughout the Solar System.", attribution: "Unknown"),
    Quote(text: "SDF backed pirates steal cargo bound for Earth.", attribution: "Unknown"),
    Quote(text: "For the SDF, it is the year 31, counted after the secession.", attribution: "Unknown"),
    Quote(text: "SetDef radicals used terrorism to extend their influence across moons, planets and asteroids.", attribution: "Unknown"),
    Quote(text: "Salen Kotch climbed to the summit of Mars' 22,000 meter shield Volcano Olympus Mons that became the namesake of his warship.", attribution: "Unknown"),
    Quote(text: "SDF Council members are \"elected\" for life.", attribution: "Unknown"),
    Quote(text: "\"Mars aeternum\" means \"Mars eternally\".", attribution: "Unknown"),
    Quote(text: "Gun possession is mandatory in SDF controlled territory.", attribution: "Unknown"),
    Quote(text: "Items from Earth are considered contraband in SDF territory.", attribution: "Unknown"),
    Quote(text: "SDF soldiers use an experimental drug that allows fighters to march 55 miles (88.5 kilometers) without fatigue.", attribution: "Unknown")
]

let sdfHighCouncilQuotes: [Quote] = [
    Quote(text: "The Earth born impede the progress of the SDF doctrine.", attribution: "The SDF High Council"),
    Quote(text: "Mars control of the Earth is the only measure of right and wrong.", attribution: "The SDF High Council"),
    Quote(text: "The SDF state is the only lasting absolute in the solar system.", attribution: "The SDF High Council"),
    Quote(text: "Freedom has no place in the light of our sun.", attribution: "The SDF High Council"),
    Quote(text: "The function of a citizen and a soldier are one.", attribution: "The SDF High Council"),
    Quote(text: "Freedom is a mark of stupidity and cowardice.", attribution: "The SDF High Council"),
    Quote(text: "The only invincible army on Earth will be the SDF.", attribution: "The SDF High Council"),
    Quote(text: "Freedom is a fundamental Earth born flaw.", attribution: "The SDF High Council"),
    Quote(text: "All Earthen shall submit to unconditional obedience without exception.", attribution: "The SDF High Council"),
    Quote(text: "SDF activities must focus on bringing about the end of the free Earth.", attribution: "The SDF High Council"),
    Quote(text: "Let us use dagger, bullet and bomb to prove the victor.", attribution: "The SDF High Council"),
    Quote(text: "The Earth has outstayed its welcome.", attribution: "The SDF High Council")
]

let salenKotchQuotes: [Quote] = [
    Quote(text: "Our world is beginning- theirs is dying.", attribution: "Admiral Salen Kotch"),
    Quote(text: "Those who want to live must wage war, and those who do not want war don't deserve to live.", attribution: "Salen Kotch"),
    Quote(text: "Death is no disgrace.", attribution: "Salen Kotch"),
    Quote(text: "We do not mourn the dead, we arm the living.", attribution: "Salen Kotch"),
    Quote(text: "Earth will not be permitted to maintain industry, sustain economy, or enable itself to rearm.", attribution: "Salen Kotch"),
    Quote(text: "Any regime without the intention to wage war is senseless and useless.", attribution: "Salen Kotch"),
    Quote(text: "We will force the Earth to braid the ropes from which they hang.", attribution: "Salen Kotch")
]

let sdfProverbs: [Quote] = [
    Quote(text: "The days of individual happiness have passed away.", attribution: "SDF proverb"),
    Quote(text: "Victory outlasts truth.", attribution: "SDF proverb")
]

let modernWarfareRemasteredQuotes: [Quote] = [ // swiftlint:disable:this inclusive_language
    Quote(text: "The future influences the present just as much as the past.", attribution: "Friedrich Nietzsche"),
    Quote(text: "You cannot escape the responsibility of tomorrow by evading it today.", attribution: "Abraham Lincoln"),
    Quote(text: "Study the past if you would define the future.", attribution: "Confucius"),
    Quote(text: "Do your duty a little more and the future will take care of itself.", attribution: "Andrew Carnegie")
]
