name: Block PR with "do-not-merge" Label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for "do-not-merge" label
        id: check-label
        run: |
          # Get the labels of the PR
          labels=$(jq -r '.pull_request.labels[]?.name // empty' "$GITHUB_EVENT_PATH")

          # Debug: print labels
          echo "Labels on the PR: $labels"

          # Check if "do-not-merge" exists in labels
          if echo "$labels" | grep -q "do-not-merge"; then
            echo "The PR is labeled as 'do-not-merge'. Failing the check."
            exit 1
          fi
