name: Block "Do Not Merge" PRs

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  block_do_not_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "do-not-merge" label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the pull request details
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          REPO="${{ github.repository }}"
          PR_LABELS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                          "https://api.github.com/repos/$REPO/issues/$PR_NUMBER" | jq -r '.labels[].name')

          # Block PR if "do-not-merge" label is present
          if echo "$PR_LABELS" | grep -q "do-not-merge"; then
            echo "❌ This PR is labeled with 'do-not-merge'. Please remove the label to proceed."
            exit 1
          else
            echo "✅ This PR does not have the 'do-not-merge' label."
          fi
