name: Build Xcode Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build Project
        run: xcodebuild -scheme MomCare -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' clean build
