name: SwiftLint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.swift"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    name: Lint with swiftlint, fail if any errors
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --strict --quiet --reporter github-actions-logging
