name: Swiftformat

on:
  push:
    branches:
      - main
    paths:
      - "**/*.swift"
      - "**/*.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.swift"
      - "**/*.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  Swiftformat:
    name: Lint with swiftformat, fail if any errors
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Swiftformat
        run: |
          brew install swiftformat

      - name: Run Swiftformat
        continue-on-error: true
        run: |
          swiftformat --quiet --strict --reporter github-actions-log --lint .

  label-swiftformat-status:
    needs: Swiftformat
    if: always() && ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add swiftformat-pass label if lint succeeded
        if: ${{ needs.Swiftformat.result == 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['swiftformat-pass']
            })
      - name: Add swiftformat-fail label if lint failed
        if: ${{ needs.Swiftformat.result == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['swiftformat-fail']
            })